list_of_prblem_links = [
    "https://www.spoj.com/problems/KAMOL/",
    "https://www.spoj.com/problems/COUINF/",
    "https://www.spoj.com/problems/PRF00/",
    "https://www.spoj.com/problems/TESTINT/",
    "https://www.spoj.com/problems/BSCXOR/",
    "https://www.spoj.com/problems/SMPWOW/",
    "https://www.spoj.com/problems/CHITEST1/",
    "https://www.spoj.com/problems/AVRG/",
    "https://www.spoj.com/problems/HRECURS/",
    "https://www.spoj.com/problems/SMPSUM/",
    "https://www.spoj.com/problems/ALCATRAZ1/",
    "https://www.spoj.com/problems/FUCT_FOR_FNPN/",
    "https://www.spoj.com/problems/SMPDIV/",
    "https://www.spoj.com/problems/FUCT_IF_COMPARE/",
    "https://www.spoj.com/problems/STRHH/",
    "https://www.spoj.com/problems/PCROSS1/",
    "https://www.spoj.com/problems/DHRODD/",
    "https://www.spoj.com/problems/CPTTRN1/",
    "https://www.spoj.com/problems/CPTTRN2/",
    "https://www.spoj.com/problems/CPTTRN3/",
    "https://www.spoj.com/problems/CPTTRN4/",
    "https://www.spoj.com/problems/CPTTRN5/",
    "https://www.spoj.com/problems/CPTTRN6/",
    "https://www.spoj.com/problems/CPTTRN7/",
    "https://www.spoj.com/problems/PRIONPRI",
    "https://www.spoj.com/problems/SMPCIRC/",
    "https://www.spoj.com/problems/HS12MBR/",
    "https://www.spoj.com/problems/SMPSEQ3/",
    "https://www.spoj.com/problems/SMPSEQ4/",
    "https://www.spoj.com/problems/SMPSEQ5/",
    "https://www.spoj.com/problems/SMPSEQ6/",
    "https://www.spoj.com/problems/SMPSEQ7/",
    "https://www.spoj.com/problems/SMPSEQ8/",
    "https://www.spoj.com/problems/SMPSEQ9/",
    "https://www.spoj.com/problems/LASTDIG/",
    "https://www.spoj.com/problems/SMPCPH1/",
    "https://www.spoj.com/problems/PRF0101/",
    "https://www.spoj.com/problems/FUCT_IF_CHECKNUM/",
    "https://www.spoj.com/problems/PRF0102/",
    "https://www.spoj.com/problems/FUCT_IF_SQRT/",
    "https://www.spoj.com/problems/PRF01IF01/",
    "https://www.spoj.com/problems/PRF01IF02/",
    "https://www.spoj.com/problems/PRF01IF03/",
    "https://www.spoj.com/problems/PRF01IF04/",
    "https://www.spoj.com/problems/PRF02LOOP01/",
    "https://www.spoj.com/problems/PRF02LOOP02/",
    "https://www.spoj.com/problems/PRF02LOOP03/",
    "https://www.spoj.com/problems/PRF02LOOP04/",
    "https://www.spoj.com/problems/AARTDARK/",
    "https://www.spoj.com/problems/ABNDNTNM/",
    "https://www.spoj.com/problems/ADABEHIVE/",
    "https://www.spoj.com/problems/BTCK/",
    "https://www.spoj.com/problems/BUET19B/",
    "https://www.spoj.com/problems/CHI_NATURAL/",
    "https://www.spoj.com/problems/CONGRAPH/",
    "https://www.spoj.com/problems/CPOD1/",
    "https://www.spoj.com/problems/DPRSDCDR/",
    "https://www.spoj.com/problems/DRNTEAGL/",
    "https://www.spoj.com/problems/ENGCD/",
    "https://www.spoj.com/problems/ENLCD/",
    "https://www.spoj.com/problems/FCTORISE/",
    "https://www.spoj.com/problems/FIZBBZIF/",
    "https://www.spoj.com/problems/FIZZFIZZ/",
    "https://www.spoj.com/problems/G11_2/",
    "https://www.spoj.com/problems/MAX10/",
    "https://www.spoj.com/problems/MOZSACL/",
    "https://www.spoj.com/problems/MUJEO/",
    "https://www.spoj.com/problems/MUJGEO/",
    "https://www.spoj.com/problems/OVISOD/",
    "https://www.spoj.com/problems/RETO6/",
    "https://www.spoj.com/problems/SERI07/",
    "https://www.spoj.com/problems/SHOCCUR/",
    "https://www.spoj.com/problems/SIMPACR/",
    "https://www.spoj.com/problems/SIMPLPRBLM/",
    "https://www.spoj.com/problems/SUMSCALC/",
    "https://www.spoj.com/problems/SUMUNZ/",
    "https://www.spoj.com/problems/VLN/",
    "https://www.spoj.com/problems/ZDIFFSQ2/",
    "https://www.spoj.com/problems/FUCT_FOR_FNPN/",
    "https://www.spoj.com/problems/FUCT_IF_CIRCLE/",
    "https://www.spoj.com/problems/FUCT_IF_CHKDATE/",
    "https://www.spoj.com/problems/PRF04STRING01/",
    "https://www.spoj.com/problems/AR2MIN/",
    "https://www.spoj.com/problems/FUCT_IF_CYLINDER/",
    "https://www.spoj.com/problems/FUCT_FOR_FATNUM/",
    "https://www.spoj.com/problems/PRF04STRING02/",
    "https://www.spoj.com/problems/AR2SUM/",
    "https://www.spoj.com/problems/FUCT_IF_SEC2TIME/",
    "https://www.spoj.com/problems/FUCT_FOR_TRINUM/",
    "https://www.spoj.com/problems/PRF04STRING03/",
    "https://www.spoj.com/problems/AR2BOOK/",
    "https://www.spoj.com/problems/FUCT_IF_DIVIDE/",
    "https://www.spoj.com/problems/FUCT_FOR_PALIN/",
    "https://www.spoj.com/problems/FUCT_FOR_PYRAMID/",
    "https://www.spoj.com/problems/PRF0103/",
    "https://www.spoj.com/problems/PRF04STRING04/",
    "https://www.spoj.com/problems/ARBOOK2/",
    "https://www.spoj.com/problems/FUCT_FOR_ARROW/",
    "https://www.spoj.com/problems/FUCT_FOR_FACFOR/",
    "https://www.spoj.com/problems/PRF03ARRAY0101/",
    "https://www.spoj.com/problems/PRF04STRING05/",
    "https://www.spoj.com/problems/AREMPLOYEE/",
    "https://www.spoj.com/problems/FUCT_IF_SQUARE/",
    "https://www.spoj.com/problems/FUCT_FOR_REFRAC/",
    "https://www.spoj.com/problems/FUCT_FOR_SUM2DIG/",
    "https://www.spoj.com/problems/PRF03ARRAY0102/",
    "https://www.spoj.com/problems/AR1NHAPINMANG/",
    "https://www.spoj.com/problems/AR2EMPLOYEES/",
    "https://www.spoj.com/problems/FUCT_IF_RECT/",
    "https://www.spoj.com/problems/FUCT_FOR_INVPYRA/",
    "https://www.spoj.com/problems/FUCT_FOR_EXPONEN/",
    "https://www.spoj.com/problems/PRF03ARRAY0103/",
    "https://www.spoj.com/problems/AR2AVG/",
    "https://www.spoj.com/problems/FUCT_IF_TRI/",
    "https://www.spoj.com/problems/FUCT_FOR_RHOMBUS/",
    "https://www.spoj.com/problems/FUCT_FOR_PRIME/",
    "https://www.spoj.com/problems/PRF03ARRAY0104/",
    "https://www.spoj.com/problems/AR2MAX/",
]


import bs4 as bs
import requests

for problem_link in list_of_prblem_links:
    status_link = problem_link.replace("problems", "status")
    status_link = status_link[:-1] + ",*******_36a2" + "/"
    response = requests.get(status_link)
    soup = bs.BeautifulSoup(str(response.content), "lxml")
    strongs = soup.findAll("strong")

    Solved = False
    for strong in strongs:
        if strong.text == "accepted":
            Solved = True

    if Solved:
        print("Solved")
    else:
        print("Not solved yet.")
